name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  NODE_JS_VER: 18.x
  SWANKY_NODE_VER: v1.6.0
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Install & display rust toolchain
      run: |
        rustup toolchain install nightly-2023-03-05
        rustup default nightly
        rustup show
        rustup component add rust-src

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}
        restore-keys: |
          ${{ runner.os }}-rust

    - name: Check if cargo-contract exists
      id: check-cargo-contract
      continue-on-error: true
      run: cargo contract --version

    - name: Install cargo contract
      if: ${{ steps.check-cargo-contract.outcome == 'failure' }}
      run: |
        cargo +stable install cargo-dylint dylint-link
        cargo +stable install --force --locked cargo-contract

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_JS_VER }}

    - name: Install swanky-cli
      run: npm install && npm install -g @astar-network/swanky-cli

    - name: Compile contracts
      run: swanky contract compile --all -v

    - name: Test contracts
      run: cargo test --manifest-path contracts/dao/Cargo.toml
